apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: "false"
  - name: failover
    value: "false"
  - name: sentinelMasterName
    value: ""
  - name: maxRetries
    value: "3"
  - name: maxRetryBackoff
    value: "2s" 